name: example-servant-elm-auth

dependencies:
  - base
  - warp
  - aeson
  - wai-make-assets
  - servant
  - servant-auth-server
  - servant-elm
  - elm-bridge
  - wai
  - servant-server
  - text
  - transformers
  - containers
  - bytestring

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
